# Generated by Django 4.2.4 on 2023-08-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='C:/Users/DELL/OneDrive/Desktop/Miniproject/minimart/minimart/static/admin/assets/img/avatars/5.png', null=True, upload_to='photo/profile-image'),
        ),
    ]
