# Generated by Django 4.2.4 on 2023-08-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product_size',
            field=models.FloatField(max_length=5),
        ),
    ]
