# Generated by Django 4.2.4 on 2023-09-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_is_available'),
        ('store', '0002_alter_productsize_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='offer_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('valid_to', models.DateField()),
                ('discount_percentage', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productsize')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productimage')),
            ],
        ),
    ]
