# Generated by Django 4.2.4 on 2023-09-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categoryoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
    ]
