# Generated by Django 4.2.4 on 2023-09-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productsize_offer_price_categoryoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='product_image',
        ),
    ]
