# Generated by Django 4.2.4 on 2023-09-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_categoryoffer_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
