# Generated by Django 4.2.4 on 2023-09-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_categoryoffer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='product',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
