# Generated by Django 4.2.4 on 2023-09-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_categoryoffer_product_categoryoffer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='offer_price',
        ),
    ]
