# Generated by Django 4.2.4 on 2023-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productsize_product_size'),
        ('cart', '0007_alter_cartitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.productsize'),
        ),
    ]
