# Generated by Django 4.2.4 on 2023-09-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_coupons_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupons',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
