# Generated by Django 4.2.4 on 2023-09-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_usercoupons_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
