# Generated by Django 4.2.4 on 2023-09-09 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_usercoupons_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 7, 12, 0)),
            preserve_default=False,
        ),
    ]
