# Generated by Django 4.2.4 on 2023-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
