# Generated by Django 4.2.4 on 2023-08-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
